### PR TITLE
Add makefile

### PR DESCRIPTION
**Pull request by cvengler**
I created a makefile.
You can now compile the stuff with a simple `make` in the root directory

### CODE REVIEW

**Comment by cvengler** [comment]
EDIT: I removed `shell_commands.h` from the makefile because it causes errors

**Comment by ghost** [comment]
Maybe check the CC environment variable instead of assuming GCC?

**Comment by cvengler** [comment]
Done, let me squash the commits

**Comment by cvengler** [comment]
Ready for merging I think

**Comment by ghost** [comment]
The CC environment variable may not be set. Is there a way to have a default value in the makefile?

**Comment by cvengler** [comment]
The CC variable is not an enviroment variable, it is an implict variable of GNU make.
The default of it is "cc" which is just another command for gcc

https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

**Comment by ghost** [comment]
Gotcha

**Comment by tmly115** [comment]
Brilliant, Thanks a lot!

**Comment by cvengler** [comment]
No problem

**Comment by Braegans** [comment]
> The CC environment variable may not be set. Is there a way to have a default value in the makefile?

It might not be relevant here because, as noted, CC is an implicit variable. However, in gnu make (at least) the syntax you want is:

    VARIABLE ?= value

https://www.gnu.org/software/make/manual/html_node/Setting.html

**Pull request merged**
